eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    config:
      override-system-properties: false

  security:
    jwt:
      jwk-set-uri: http://localhost:9090/realms/e-commerce/protocol/openid-connect/certs
