spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecom_order
    username: postgres
    password: nguyenkhang

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

server:
  port: 8092

