spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecom_order
    username: postgres
    password: nguyenkhang

  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.khangng.order_service.kafka.OrderConfirmation

server:
  port: 8092

application:
  config:
    customer-url: http://localhost:8090/customers
    product-url: http://localhost:8091/products
    payment-url: http://localhost:8093/payments
