version: '3.7'

services:
#  postgres:
#    image: postgres:latest
#    container_name: postgres
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: postgres
#    networks:
#      - e-commerce

#  mongodb:
#    image: mongo:latest
#    container_name: mongodb
#    environment:
#        MONGO_INITDB_ROOT_USERNAME: root
#        MONGO_INITDB_ROOT_PASSWORD: root
#    ports:
#      - "27017:27017"
#    networks:
#      - e-commerce

    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        container_name: zookeeper
        ports:
        - "2181:2181"
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_SERVER_ID: 1
          ZOOKEEPER_SERVERS: zookeeper:2888:3888
        networks:
        - e-commerce

    kafka:
      image: confluentinc/cp-kafka:latest
      container_name: kafka
      ports:
        - "9092:9092"
        - "29092:29092"
      environment:
        KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
        KAFKA_BROKER_ID: 1
      networks:
        - e-commerce
      depends_on:
        - zookeeper

    mail-dev:
      container_name: ms-mail-dev
      image: maildev/maildev
      ports:
        - 1080:1080
        - 1025:1025

#    zipkin:
#      container_name: zipkin
#      image: openzipkin/zipkin
#      ports:
#        - "9411:9411"
#      networks:
#        - microservices-net

networks:
    e-commerce:
        driver: bridge