spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/ecom-gateway
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888

