keycloak:
  issuer-uri: http://localhost:9090/realms/e-commerce
  realm: e-commerce
  client-id: gateway-service

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.issuer-uri}
#          jwk-set-uri: ${keycloak.issuer-uri}/protocol/openid-connect/certs
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888

